import agencyhub from './agencyhub.svg'
import agencyprofile from './agencyprofile.svg'
import membership from './membership.svg'
import property from './property.svg'
import propertylist from './propertylist.svg'
import agents from './agents.svg'
import lead from './lead.svg'
import contacts from './contacts.svg'
import markting from './markting.svg'
import aqarat from './aqarat.svg'
import notification from './notification.svg'
import team from './team.svg'
import arrowr from './arrowr.svg'
import arrowl from './arrowl.svg'
import arrowt from './arrowt.svg'
import arrowb from './arrowb.svg'
import circle from './circle.svg'
import upload from "./upload.svg"
import defaultImage from  "./defaultImage.svg"
import login from "./login.svg"
import aqarat1 from './aqarat1.svg'
import menu from './menu.svg'
import fillter from './fillter.svg'
import date from './date.svg'
import size from "./size.svg"
import Cheques from './Cheques.svg'
import bedroom from './bedroom.svg'
import bathroom from './bathroom.svg'
import Amenities from './Amenities.svg'
import ownershipImg from './ownershipImg.svg'
import charge from './charge.svg'
import toronto from './toronto.svg'

export {toronto,size,ownershipImg ,charge ,Cheques,bedroom, bathroom,Amenities,aqarat1 ,menu, agencyhub,agencyprofile,membership,property,propertylist,agents,lead,markting,contacts,aqarat,notification,team,arrowb,arrowt,arrowl,arrowr ,circle ,upload,defaultImage , login ,fillter,date}